# Generated by Django 3.2.4 on 2021-07-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('travel_date_from', models.DateTimeField()),
                ('travel_date_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='trips', to='Travel_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
